name: homebrew

on:
  release:
    types: [published]
  workflow_dispatch: ~

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v2
        with:
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-formulas
          github_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit_owner: Justintime50
          commit_email: 39606064+Justintime50@users.noreply.github.com
          update_readme_table: true
          install: |
            (prefix/"muffin").install Dir["dist/*"]
            bin.install_symlink prefix/"muffin/muffin" => "muffin"
          test: 'assert_match "Muffin", shell_output("#{bin}/muffin --version")'
